const {mathjax} = require('mathjax-full/js/mathjax.js');
const {TeX} = require('mathjax-full/js/input/tex.js');
const {SVG} = require('mathjax-full/js/output/svg.js');
const {jsdomAdaptor} = require('mathjax-full/js/adaptors/jsdomAdaptor.js');
const {RegisterHTMLHandler} = require('mathjax-full/js/handlers/html.js');
const {AssistiveMmlHandler} = require('mathjax-full/js/a11y/assistive-mml.js');
const {AllPackages} = require('mathjax-full/js/input/tex/AllPackages.js');
const {JSDOM} = require('jsdom');
require('mathjax-full/js/util/entities/all.js');
const htmlfile = require('fs').readFileSync("/home/keane/WebstormProjects/jijian/public/v2/detail/atcoder-abc-194/index.html", 'utf8');
const adaptor = jsdomAdaptor(JSDOM);
AssistiveMmlHandler(RegisterHTMLHandler(adaptor));
const tex = new TeX();
const svg = new SVG();
const html = mathjax.document(htmlfile, {InputJax: tex, OutputJax: svg});
html.render();
console.log(adaptor.doctype(html.document));
require('fs').writeFileSync('./a.html',adaptor.doctype(html.document));
console.log(adaptor.outerHTML(adaptor(html.document)));
require('fs').writeFileSync('./b.html',adaptor.outerHTML(adaptor.root(html.document)));